# Schema for Geocoder module.

geocoder.settings:
  type: config_object
  label: 'Geocoder settings'
  mapping:
    cache:
      type: boolean
      label: 'Should we cache the results ?'
      description: 'To prevent sending multiple times the same request, you can enable to cache to save temporarily the result of the geocode and reverse geocode in the cache.'
    plugins_options:
      type: sequence
      label: 'Plugins arguments'
      sequence:
        type: geocoder.settings.plugins.[%key]
        label: 'The configuration of a plugin'

geocoder.settings.plugins.googlemaps:
  type: mapping
  label: 'GoogleMaps arguments'
  mapping:
    apiKey:
      type: string
      nullable: true
      label: 'Google Geocoding API key (optional)'
      description: '<a href="https://developers.google.com/maps/documentation/javascript/get-api-key#standard-auth">Follow these steps to get an API key</a>'
    region:
      type: string
      nullable: true
      label: 'Region code for region biasing (optional)'
      description: 'See <a href="https://developers.google.com/maps/documentation/javascript/geocoding#GeocodingRegionCodes">Region code biasing</a>'

geocoder.settings.plugins.googlemaps_business:
  type: mapping
  label: 'GoogleMaps for Business arguments'
  mapping:
    clientId:
      type: string
      label: 'Client ID'
      description: '<a href="https://developers.google.com/maps/documentation/geocoding/get-api-key#client-id">Authenticating your application using a client ID and digital signature</a>'
    privateKey:
      type: string
      nullable: true
      label: 'Private key (optional)'
      description: '<a href="https://developers.google.com/maps/documentation/geocoding/get-api-key#cryptographic_signing_keys">Getting a private cryptographic key</a>'
    apiKey:
      type: string
      nullable: true
      label: 'Google Geocoding API key (optional)'
      description: '<a href="https://developers.google.com/maps/documentation/javascript/get-api-key#standard-auth">Follow these steps to get an API key</a>'
    region:
      type: string
      nullable: true
      label: 'Region code for region biasing (optional)'
      description: 'See <a href="https://developers.google.com/maps/documentation/javascript/geocoding#GeocodingRegionCodes">Region code biasing</a>'
    channel:
      type: string
      nullable: true
      label: 'Channel (optional)'
      description: 'See <a href="https://developers.google.com/maps/premium/reports/usage-reports#channels">What are channels?</a>'

geocoder.settings.plugins.arcgisonline:
  type: mapping
  label: 'ArcGISOnline arguments'
  mapping:
    sourceCountry:
      type: string
      label: 'Source country for country biasing (optional)'
      nullable: true

geocoder.settings.plugins.bingmaps:
  type: mapping
  label: 'Bingmaps arguments'
  mapping:
    apiKey:
      type: string
      label: 'API key'
      description: '<a href="https://msdn.microsoft.com/en-us/library/ff428642.aspx">Getting a Bing Maps API key</a>'

geocoder.settings.plugins.geonames:
  type: mapping
  label: 'Geonames arguments'
  mapping:
    username:
      type: string
      label: 'Username'
      description: 'Create a free user account at <a href="http://www.geonames.org/login">www.geonames.org/login</a>'

geocoder.settings.plugins.ipinfodb:
  type: mapping
  label: 'IpInfoDb arguments'
  mapping:
    apiKey:
      type: string
      label: 'API key'
      description: 'Get an API key by creating a free account at <a href="https://www.ipinfodb.com/register">www.ipinfodb.com/register</a>'
    precision:
      type: string
      nullable: true
      label: 'Precision (optional)'
      description: 'Either "city" or "country" (faster). Defaults to "city".'

geocoder.settings.plugins.mapquest:
  type: mapping
  label: 'MapQuest arguments'
  mapping:
    apiKey:
      type: string
      label: 'API key'
      description: '<a href="https://developer.mapquest.com/">Get your free API key</a>'
    licensed:
      type: boolean
      label: 'Licensed'
      description: 'Whether to use MapQuest''s licensed endpoints. Uncheck to use the open endpoints.'

geocoder.settings.plugins.maxmind:
  type: mapping
  label: 'MaxMind arguments'
  mapping:
    apiKey:
      type: string
      label: 'API key'
    service:
      type: string
      nullable: true
      label: 'MaxMind service (optional)'
      description: 'Can be either "a", "b", "f" or "e". Defaults to "f". See <a href="https://dev.maxmind.com/geoip/legacy/web-services/#Per-Service_URIs">Services</a>'

geocoder.settings.plugins.nominatim:
  type: mapping
  label: 'Nominatim arguments'
  mapping:
    rootUrl:
      type: string
      label: 'Root URL'
      description: 'Root URL of the nominatim server'
    userAgent:
      type: string
      label: 'User agent'
      description: 'Value of the User-Agent header'
    referer:
      type: string
      label: 'Referer'
      description: 'Value of the Referer header'

geocoder.settings.plugins.opencage:
  type: mapping
  label: 'OpenCage arguments'
  mapping:
    apiKey:
      type: string
      label: 'API key'
      description: 'Sign up for a free API key at <a href="https://opencagedata.com/users/sign_up">opencagedata.com/users/sign_up</a>'

geocoder.settings.plugins.tomtom:
  type: mapping
  label: 'TomTom arguments'
  mapping:
    apiKey:
      type: string
      label: 'API key'
      description: '<a href="https://developer.tomtom.com/apps/myapps">Request an evaluation API key</a>'

geocoder.settings.plugins.file:
  type: sequence
  label: 'File arguments'
  sequence:

geocoder.settings.plugins.freegeoip:
  type: sequence
  label: 'Freegeoip arguments'
  sequence:

geocoder.settings.plugins.geoip:
  type: sequence
  label: 'Geoip arguments'
  sequence:

geocoder.settings.plugins.geoplugin:
  type: sequence
  label: 'Geoplugin arguments'
  sequence:

geocoder.settings.plugins.gpxfile:
  type: sequence
  label: 'Gpxfile arguments'
  sequence:

geocoder.settings.plugins.hostip:
  type: sequence
  label: 'Hostip arguments'
  sequence:

geocoder.settings.plugins.openstreetmap:
  type: sequence
  label: 'Openstreetmap arguments'
  sequence:

geocoder.settings.plugins.random:
  type: sequence
  label: 'Random arguments'
  sequence:

geocoder.settings.plugins.yandex:
  type: sequence
  label: 'Yandex arguments'
  sequence:
